# Site settings ...
uri: https://hachiaaa.github.io
url: https://hachiaaa.github.io
name: Wang GuoQi
title: ğŸŸ
author: wangguoqi
keywords: "Personal blog"
description: "ğŸ‘‹ My name is wang guoqi, I explain with codes and words"
github_username: Hachiaaa
twitter_username: kingguoqi

# Build settings ...
sass:
  style: compressed
markdown: kramdown
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"
exclude:
  - README.md

# Plugins ...
plugins:
  - jekyll-paginate
  - jemoji
